// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgtUejJ8WagwdzmU9z6CYT-QKCdMqQXQ',
    appId: '1:938644013538:web:845077653cc75ebf3ef9bb',
    messagingSenderId: '938644013538',
    projectId: 'bookreview-app-example',
    authDomain: 'bookreview-app-example.firebaseapp.com',
    storageBucket: 'bookreview-app-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw53vFfIna0-M244sN0XoIcmSE_4oQaJI',
    appId: '1:938644013538:android:d6a1ef0b3e6a8b083ef9bb',
    messagingSenderId: '938644013538',
    projectId: 'bookreview-app-example',
    storageBucket: 'bookreview-app-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbst-DwrBA5V2oKQzoCtEdo1_hj1qyvA',
    appId: '1:938644013538:ios:ea63d79422ed6e313ef9bb',
    messagingSenderId: '938644013538',
    projectId: 'bookreview-app-example',
    storageBucket: 'bookreview-app-example.appspot.com',
    iosClientId: '938644013538-l4cav1n8gbggvrosmujvqncimrrlf8r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookreview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbst-DwrBA5V2oKQzoCtEdo1_hj1qyvA',
    appId: '1:938644013538:ios:5db2d20a327a26c13ef9bb',
    messagingSenderId: '938644013538',
    projectId: 'bookreview-app-example',
    storageBucket: 'bookreview-app-example.appspot.com',
    iosClientId: '938644013538-09jesbnnqiu7r0bpmh8npkdu9vlnqsk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookreview.RunnerTests',
  );
}
